import bs4
import requests
import csv

def function1():

    base_url = "https://www.bd-pratidin.com"
    catagory = "sports"
    #next_page = "18"

    national_catagory = [""]

    all_url = []
    i=0
    for page_index in national_catagory:
        i=i+1
        if i==1:
            complete_url =  base_url + '/' + catagory + '/'#+ next_page + '/'
            #print(complete_url + '18')
            #print(complete_url + '36')
        else:
            complete_url = base_url + '/' + catagory + '/' +str(page_index)
            #print(complete_url + '18')
            #print(complete_url + '36')
        #all_url.append([complete_url])
        all_url.append([complete_url+'14'])
        all_url.append([complete_url + '28'])
        all_url.append([complete_url + '42'])
        all_url.append([complete_url + '56'])
        all_url.append([complete_url + '70'])
        all_url.append([complete_url + '84'])
        all_url.append([complete_url + '98'])
        all_url.append([complete_url + '112'])
        all_url.append([complete_url + '126'])
        all_url.append([complete_url + '140'])
        all_url.append([complete_url + '154'])
        all_url.append([complete_url + '168'])
        all_url.append([complete_url + '260'])
        all_url.append([complete_url + '182'])
        all_url.append([complete_url + '196'])
        all_url.append([complete_url + '210'])
        all_url.append([complete_url + '224'])
        all_url.append([complete_url + '238'])
        all_url.append([complete_url + '252'])
        all_url.append([complete_url + '266'])
        all_url.append([complete_url + '280'])
        all_url.append([complete_url + '294'])
        all_url.append([complete_url + '308'])
        all_url.append([complete_url + '322'])
        all_url.append([complete_url + '336'])
        all_url.append([complete_url + '350'])
        all_url.append([complete_url + '364'])
        all_url.append([complete_url + '378'])
        all_url.append([complete_url + '392'])
        all_url.append([complete_url + '406'])
        all_url.append([complete_url + '420'])
        all_url.append([complete_url + '434'])
        all_url.append([complete_url + '448'])
        all_url.append([complete_url + '462'])
        all_url.append([complete_url + '476'])
        all_url.append([complete_url + '490'])
        all_url.append([complete_url + '504'])
        all_url.append([complete_url + '518'])
        all_url.append([complete_url + '532'])
        all_url.append([complete_url + '546'])
        all_url.append([complete_url + '560'])
        all_url.append([complete_url + '574'])
        all_url.append([complete_url + '588'])
        all_url.append([complete_url + '602'])
        all_url.append([complete_url + '616'])
        all_url.append([complete_url + '630'])
        all_url.append([complete_url + '644'])
        all_url.append([complete_url + '658'])
        all_url.append([complete_url + '672'])
        all_url.append([complete_url + '686'])
        all_url.append([complete_url + '700'])
        all_url.append([complete_url + '714'])
        all_url.append([complete_url + '728'])
        all_url.append([complete_url + '742'])
        all_url.append([complete_url + '756'])
        all_url.append([complete_url + '770'])
        all_url.append([complete_url + '784'])
        all_url.append([complete_url + '798'])
        all_url.append([complete_url + '812'])
        all_url.append([complete_url + '826'])
        all_url.append([complete_url + '840'])
        all_url.append([complete_url + '854'])
        all_url.append([complete_url + '868'])
        all_url.append([complete_url + '882'])
        all_url.append([complete_url + '896'])
        all_url.append([complete_url + '910'])
        all_url.append([complete_url + '924'])
        all_url.append([complete_url + '938'])
        all_url.append([complete_url + '952'])
        all_url.append([complete_url + '966'])
        all_url.append([complete_url + '980'])
        all_url.append([complete_url + '994'])
        all_url.append([complete_url + '1008'])
        all_url.append([complete_url + '1022'])
        all_url.append([complete_url + '1036'])
        all_url.append([complete_url + '1050'])
        all_url.append([complete_url + '1064'])
        all_url.append([complete_url + '1078'])
        all_url.append([complete_url + '1092'])
        all_url.append([complete_url + '1106'])
        all_url.append([complete_url + '1120'])
        all_url.append([complete_url + '1134'])
        all_url.append([complete_url + '1148'])
        all_url.append([complete_url + '1162'])
        all_url.append([complete_url + '1176'])
        all_url.append([complete_url + '1190'])
        all_url.append([complete_url + '1204'])
        all_url.append([complete_url + '1218'])
        all_url.append([complete_url + '1232'])
        all_url.append([complete_url + '1246'])
        all_url.append([complete_url + '1260'])
        all_url.append([complete_url + '1274'])
        all_url.append([complete_url + '1288'])
        all_url.append([complete_url + '1302'])
        all_url.append([complete_url + '1316'])
        all_url.append([complete_url + '1330'])
        all_url.append([complete_url + '1344'])
        all_url.append([complete_url + '1358'])
        all_url.append([complete_url + '1372'])
        all_url.append([complete_url + '1386'])
        all_url.append([complete_url + '1400'])
        all_url.append([complete_url + '1414'])
        all_url.append([complete_url + '1428'])
        all_url.append([complete_url + '1442'])
        all_url.append([complete_url + '1456'])
        all_url.append([complete_url + '1470'])
        all_url.append([complete_url + '1484'])
        all_url.append([complete_url + '1498'])
        all_url.append([complete_url + '1512'])
        all_url.append([complete_url + '1526'])
        all_url.append([complete_url + '1540'])
        all_url.append([complete_url + '1554'])
        all_url.append([complete_url + '1568'])
        all_url.append([complete_url + '1582'])
        all_url.append([complete_url + '1596'])
        all_url.append([complete_url + '1610'])
        all_url.append([complete_url + '1624'])
        all_url.append([complete_url + '1638'])
        all_url.append([complete_url + '1652'])
        all_url.append([complete_url + '1666'])
        all_url.append([complete_url + '1680'])
        all_url.append([complete_url + '1694'])
        all_url.append([complete_url + '1708'])
        all_url.append([complete_url + '1722'])
        all_url.append([complete_url + '1736'])
        all_url.append([complete_url + '1750'])
        all_url.append([complete_url + '1764'])
        all_url.append([complete_url + '1778'])
        all_url.append([complete_url + '1792'])
        all_url.append([complete_url + '1806'])
        all_url.append([complete_url + '1820'])
        all_url.append([complete_url + '1834'])
        all_url.append([complete_url + '1848'])
        all_url.append([complete_url + '1862'])
        all_url.append([complete_url + '1876'])
        all_url.append([complete_url + '1890'])
        all_url.append([complete_url + '1904'])
        all_url.append([complete_url + '1918'])
        all_url.append([complete_url + '1932'])
        all_url.append([complete_url + '1946'])
        all_url.append([complete_url + '1960'])
        all_url.append([complete_url + '1974'])
        all_url.append([complete_url + '1988'])
        all_url.append([complete_url + '2002'])
        all_url.append([complete_url + '2016'])
        all_url.append([complete_url + '2030'])
        all_url.append([complete_url + '2044'])
        all_url.append([complete_url + '2058'])
        all_url.append([complete_url + '2072'])
        all_url.append([complete_url + '2086'])
        all_url.append([complete_url + '2100'])
        all_url.append([complete_url + '2114'])
        all_url.append([complete_url + '2128'])
        all_url.append([complete_url + '2142'])
        all_url.append([complete_url + '2156'])
        all_url.append([complete_url + '2170'])
        all_url.append([complete_url + '2184'])
        all_url.append([complete_url + '2198'])
        all_url.append([complete_url + '2212'])
        all_url.append([complete_url + '2226'])
        all_url.append([complete_url + '2240'])
        all_url.append([complete_url + '2254'])
        all_url.append([complete_url + '2268'])
        all_url.append([complete_url + '2282'])
        all_url.append([complete_url + '2296'])
        all_url.append([complete_url + '2310'])
        all_url.append([complete_url + '2324'])
        all_url.append([complete_url + '2338'])
        all_url.append([complete_url + '2352'])
        all_url.append([complete_url + '2366'])
        all_url.append([complete_url + '2380'])
        all_url.append([complete_url + '2394'])
        all_url.append([complete_url + '2408'])
        all_url.append([complete_url + '2422'])
        all_url.append([complete_url + '2436'])
        all_url.append([complete_url + '2450'])
        all_url.append([complete_url + '2464'])
        all_url.append([complete_url + '2478'])
        all_url.append([complete_url + '2492'])
        all_url.append([complete_url + '2506'])
        all_url.append([complete_url + '2520'])
        all_url.append([complete_url + '2534'])
        all_url.append([complete_url + '2548'])
        all_url.append([complete_url + '2562'])
        all_url.append([complete_url + '2576'])
        all_url.append([complete_url + '2590'])
        all_url.append([complete_url + '2604'])
        all_url.append([complete_url + '2618'])
        all_url.append([complete_url + '2632'])
        all_url.append([complete_url + '2646'])
        all_url.append([complete_url + '2660'])
        all_url.append([complete_url + '2674'])
        all_url.append([complete_url + '2688'])
        all_url.append([complete_url + '2702'])
        all_url.append([complete_url + '2716'])
        all_url.append([complete_url + '2730'])
        all_url.append([complete_url + '2744'])
        all_url.append([complete_url + '2758'])
        all_url.append([complete_url + '2772'])
        all_url.append([complete_url + '2786'])
        all_url.append([complete_url + '2800'])
        all_url.append([complete_url + '2814'])
        all_url.append([complete_url + '2828'])
        all_url.append([complete_url + '2842'])
        all_url.append([complete_url + '2456'])
        all_url.append([complete_url + '2870'])
        all_url.append([complete_url + '2884'])
        all_url.append([complete_url + '2898'])
        all_url.append([complete_url + '2912'])
        all_url.append([complete_url + '2926'])
        all_url.append([complete_url + '2940'])
        all_url.append([complete_url + '2954'])
        all_url.append([complete_url + '2968'])
        all_url.append([complete_url + '2982'])
        all_url.append([complete_url + '2996'])
        all_url.append([complete_url + '3010'])
        all_url.append([complete_url + '3024'])
        all_url.append([complete_url + '3038'])
        all_url.append([complete_url + '3052'])
        all_url.append([complete_url + '3066'])
        all_url.append([complete_url + '3080'])
        all_url.append([complete_url + '3094'])
        all_url.append([complete_url + '3108'])
        all_url.append([complete_url + '3122'])
        all_url.append([complete_url + '3136'])
        all_url.append([complete_url + '3150'])
        all_url.append([complete_url + '3164'])
        all_url.append([complete_url + '3178'])
        all_url.append([complete_url + '3192'])
        all_url.append([complete_url + '3206'])
        all_url.append([complete_url + '3220'])
        all_url.append([complete_url + '3234'])
        all_url.append([complete_url + '3248'])
        all_url.append([complete_url + '3262'])
        all_url.append([complete_url + '3276'])
        all_url.append([complete_url + '3290'])
        all_url.append([complete_url + '3304'])
        all_url.append([complete_url + '3318'])
        all_url.append([complete_url + '3332'])
        all_url.append([complete_url + '3346'])
        all_url.append([complete_url + '3360'])
        all_url.append([complete_url + '3374'])
        all_url.append([complete_url + '3388'])
        all_url.append([complete_url + '3402'])
        all_url.append([complete_url + '3416'])
        all_url.append([complete_url + '3430'])
        all_url.append([complete_url + '3444'])
        all_url.append([complete_url + '3458'])
        all_url.append([complete_url + '3472'])
        all_url.append([complete_url + '3486'])
        all_url.append([complete_url + '3500'])
        all_url.append([complete_url + '3514'])
        all_url.append([complete_url + '3528'])
        all_url.append([complete_url + '3542'])
        all_url.append([complete_url + '3556'])
        all_url.append([complete_url + '3570'])
        all_url.append([complete_url + '3584'])
        all_url.append([complete_url + '3598'])
        all_url.append([complete_url + '3612'])
        all_url.append([complete_url + '3626'])
        all_url.append([complete_url + '3640'])
        all_url.append([complete_url + '3654'])
        all_url.append([complete_url + '3668'])
        all_url.append([complete_url + '3682'])
        all_url.append([complete_url + '3696'])
        all_url.append([complete_url + '3710'])
        all_url.append([complete_url + '3724'])
        all_url.append([complete_url + '3738'])
        all_url.append([complete_url + '3752'])
        all_url.append([complete_url + '3766'])
        all_url.append([complete_url + '3780'])
        all_url.append([complete_url + '3794'])
        all_url.append([complete_url + '3808'])
        all_url.append([complete_url + '3822'])
        all_url.append([complete_url + '3836'])









    with open('main_page_url.csv',mode = 'w', newline='') as main_url_list:
        main_url_writer = csv.writer(main_url_list,delimiter = ',', quotechar='"', quoting=csv.QUOTE_MINIMAL)

        for url in all_url:
            print(url)
            main_url_writer.writerow(url)

    main_url_list.close()
    return all_url
function1()
